# Generated by Django 5.1.1 on 2024-09-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_alter_sitesetup_options_menulink_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='new_tab',
            field=models.BooleanField(default=True),
        ),
    ]
