# Generated by Django 5.1.2 on 2024-10-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
