# Generated by Django 5.1.2 on 2024-10-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_menulink_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulink',
            options={'ordering': ['order'], 'verbose_name': 'Menu Link', 'verbose_name_plural': 'Menu Links'},
        ),
        migrations.AlterField(
            model_name='menulink',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
